"""add_categories_teams_timers_penalties

Revision ID: 155bd42ed3f3
Revises: b06981e12e58
Create Date: 2026-03-09 23:08:36.951853

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '155bd42ed3f3'
down_revision: Union[str, None] = 'b06981e12e58'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('competition_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('category_type', sa.Enum('individual', 'team', name='categorytype'), nullable=False),
    sa.Column('max_team_size', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['competition_id'], ['competitions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_categories_competition_id'), 'categories', ['competition_id'], unique=False)
    op.create_index(op.f('ix_categories_id'), 'categories', ['id'], unique=False)
    op.create_table('penalty_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('competition_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('kind', sa.String(length=50), nullable=False),
    sa.Column('seconds', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['competition_id'], ['competitions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_penalty_types_competition_id'), 'penalty_types', ['competition_id'], unique=False)
    op.create_index(op.f('ix_penalty_types_id'), 'penalty_types', ['id'], unique=False)
    op.create_table('competitor_registrations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('competition_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('document', sa.String(length=30), nullable=True),
    sa.Column('bib_number', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['competition_id'], ['competitions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'competition_id', name='uq_competitor_competition')
    )
    op.create_index(op.f('ix_competitor_registrations_category_id'), 'competitor_registrations', ['category_id'], unique=False)
    op.create_index(op.f('ix_competitor_registrations_competition_id'), 'competitor_registrations', ['competition_id'], unique=False)
    op.create_index(op.f('ix_competitor_registrations_id'), 'competitor_registrations', ['id'], unique=False)
    op.create_index(op.f('ix_competitor_registrations_user_id'), 'competitor_registrations', ['user_id'], unique=False)
    op.create_table('teams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('competition_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('captain_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['captain_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['competition_id'], ['competitions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_teams_category_id'), 'teams', ['category_id'], unique=False)
    op.create_index(op.f('ix_teams_competition_id'), 'teams', ['competition_id'], unique=False)
    op.create_index(op.f('ix_teams_id'), 'teams', ['id'], unique=False)
    op.create_table('team_members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('team_id', 'user_id', name='uq_team_member')
    )
    op.create_index(op.f('ix_team_members_id'), 'team_members', ['id'], unique=False)
    op.create_index(op.f('ix_team_members_team_id'), 'team_members', ['team_id'], unique=False)
    op.create_index(op.f('ix_team_members_user_id'), 'team_members', ['user_id'], unique=False)
    op.create_table('timers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('competition_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('idle', 'running', 'stopped', 'finished', name='timerstatus'), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('stopped_at', sa.DateTime(), nullable=True),
    sa.Column('elapsed_seconds', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['competition_id'], ['competitions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_timers_category_id'), 'timers', ['category_id'], unique=False)
    op.create_index(op.f('ix_timers_competition_id'), 'timers', ['competition_id'], unique=False)
    op.create_index(op.f('ix_timers_id'), 'timers', ['id'], unique=False)
    op.create_index(op.f('ix_timers_team_id'), 'timers', ['team_id'], unique=False)
    op.create_index(op.f('ix_timers_user_id'), 'timers', ['user_id'], unique=False)
    op.create_table('penalties',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timer_id', sa.Integer(), nullable=False),
    sa.Column('penalty_type_id', sa.Integer(), nullable=False),
    sa.Column('applied_by_id', sa.Integer(), nullable=True),
    sa.Column('justification', sa.Text(), nullable=False),
    sa.Column('seconds_added', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['applied_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['penalty_type_id'], ['penalty_types.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['timer_id'], ['timers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_penalties_id'), 'penalties', ['id'], unique=False)
    op.create_index(op.f('ix_penalties_timer_id'), 'penalties', ['timer_id'], unique=False)
    op.create_table('timer_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timer_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.Enum('start', 'stop', 'restart', 'finish', name='timereventtype'), nullable=False),
    sa.Column('triggered_by_id', sa.Integer(), nullable=True),
    sa.Column('note', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['timer_id'], ['timers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['triggered_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_timer_events_id'), 'timer_events', ['id'], unique=False)
    op.create_index(op.f('ix_timer_events_timer_id'), 'timer_events', ['timer_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_timer_events_timer_id'), table_name='timer_events')
    op.drop_index(op.f('ix_timer_events_id'), table_name='timer_events')
    op.drop_table('timer_events')
    op.drop_index(op.f('ix_penalties_timer_id'), table_name='penalties')
    op.drop_index(op.f('ix_penalties_id'), table_name='penalties')
    op.drop_table('penalties')
    op.drop_index(op.f('ix_timers_user_id'), table_name='timers')
    op.drop_index(op.f('ix_timers_team_id'), table_name='timers')
    op.drop_index(op.f('ix_timers_id'), table_name='timers')
    op.drop_index(op.f('ix_timers_competition_id'), table_name='timers')
    op.drop_index(op.f('ix_timers_category_id'), table_name='timers')
    op.drop_table('timers')
    op.drop_index(op.f('ix_team_members_user_id'), table_name='team_members')
    op.drop_index(op.f('ix_team_members_team_id'), table_name='team_members')
    op.drop_index(op.f('ix_team_members_id'), table_name='team_members')
    op.drop_table('team_members')
    op.drop_index(op.f('ix_teams_id'), table_name='teams')
    op.drop_index(op.f('ix_teams_competition_id'), table_name='teams')
    op.drop_index(op.f('ix_teams_category_id'), table_name='teams')
    op.drop_table('teams')
    op.drop_index(op.f('ix_competitor_registrations_user_id'), table_name='competitor_registrations')
    op.drop_index(op.f('ix_competitor_registrations_id'), table_name='competitor_registrations')
    op.drop_index(op.f('ix_competitor_registrations_competition_id'), table_name='competitor_registrations')
    op.drop_index(op.f('ix_competitor_registrations_category_id'), table_name='competitor_registrations')
    op.drop_table('competitor_registrations')
    op.drop_index(op.f('ix_penalty_types_id'), table_name='penalty_types')
    op.drop_index(op.f('ix_penalty_types_competition_id'), table_name='penalty_types')
    op.drop_table('penalty_types')
    op.drop_index(op.f('ix_categories_id'), table_name='categories')
    op.drop_index(op.f('ix_categories_competition_id'), table_name='categories')
    op.drop_table('categories')
    # ### end Alembic commands ###
